# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsArticle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsArticle

  pod 'PKHUD', '~> 5.0'
  pod 'SDWebImage'
  
  target 'NewsArticleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsArticleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
